apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        {{- if .Values.initContainer.enabled }}
        - name: download-spi-and-theme
          image: amazon/aws-cli:latest  # Includes awscli and unzip
          command:
            - sh
            - -c
            - |
              # Download SPIs
              {{- range .Values.initContainer.s3.spiKeys }}
              aws s3 cp s3://{{ $.Values.initContainer.s3.bucket }}/{{ . }} /providers/$(basename {{ . | quote }}) || echo "Failed to download SPI: {{ . }}"
              {{- end }}

              # Download and extract themes
              {{- range .Values.initContainer.s3.themeKeys }}
              aws s3 cp s3://{{ $.Values.initContainer.s3.bucket }}/{{ . }} /tmp/$(basename {{ . | quote }}) || echo "Failed to download theme: {{ . }}"
              unzip /tmp/$(basename {{ . | quote }}) -d /themes/ || echo "Failed to unzip theme: {{ . }}"
              mv /themes/$(basename {{ . | quote }} | sed 's/\.zip$//') /themes/$(basename {{ . | quote }} | sed 's/\.zip$//') || echo "Failed to move theme: {{ . }}"
              rm /tmp/$(basename {{ . | quote }})
              {{- end }}
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-access-key
            - name: AWS_REGION
              value: {{ .Values.initContainer.s3.region | quote }}
            - name: AWS_SESSION_TOKEN
              value: IQoJb3JpZ2luX2VjEA0aCXVzLWVhc3QtMSJGMEQCIG5nSOxaT8ytEgK/bU+ii9Qwpljet5Gc2srjEAdrPS9NAiB/8kUl23M7XuAubIw53hWzvfNXpo+5eBFn2guj6SXxwiqLAwhmEAAaDDc4NTA2MjMwMTg3OSIMmNSQlfGvUuUL0wxOKugCpKI5PP2JRKjc+FWszD0jLwSqG7ZN1aolrX4ZZg3BwrYslWbTuYWi6Qa1c92iJxQSp1eYF7JV44mJgOHji6Fthwp9NWF2Yf7II7Xwuj0mNGKCCpvlYy5d3gJSr8uqe0qlWgAQXh91jsOts8iTNfHHzwbr2fMlEuaxIOTasJCCb3Pq1kKcgKFmT/ktwPVYbHBcoYWfOtUWUqyE61+QIcxyvzBNJpKcHy4Y7Gph01NX+M3eq4GkD2NmrmPqNBmpthDIm20FugEOqjdSXxqhdY/lbl976Ml6z8J9fO9voO4WWlX/RQVApBZIGHMgswTu6j+9h1WpNwToFpMTluUyRW0TWP6aCQBK8d7R3cDIeS0OrgYY5tZkB4GRuVBQV6AnuZvfaWLj1GpoVGRBG/6ncGEpnKb0HNoQPqdfpuLsm6d/EQWq0CZOd3M/C5EWnn4TLapk675PtSZvDKQsWAAr4gVfjHXnyzaPRvaAMNG3574GOqcB7qTWUVe9uY8MjqbSRZXKftpgTCF8Gij69JK5pRO0dXcMSCQqIgGK7447Xv2ZRTpX3jpM8Gtxe2Z/n03TUSQFRhgJTag13reZxRKPnOWKaMlYzzuUg9CxLk55x2hJOBTwYRLJ+7tF3pqkhYNuOp8lF/c64Atf3XJyH8SCqAHZewfgr2eqYcpCGzwn8NLu+W5PRjSAc9mFQQdd3t8IUmTb2y5C9/51e6A=
          volumeMounts:
            - name: providers
              mountPath: /providers
            - name: themes
              mountPath: /themes
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/opt/keycloak/bin/kc.sh"
          args:
            - {{ .Values.start.mode }}
            {{- range .Values.start.options }}
            - {{ . | quote }}
            {{- end }}
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.env.KEYCLOAK_ADMIN | quote }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.env.KEYCLOAK_ADMIN_PASSWORD | quote }}
            - name: PROXY_ADDRESS_FORWARDING
              value: {{ .Values.env.PROXY_ADDRESS_FORWARDING | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /opt/keycloak/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "keycloak.fullname" . }}-pvc
        - name: providers
          emptyDir: {}
        - name: themes
          emptyDir: {}