apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        {{- if .Values.initContainer.enabled }}
        - name: download-spi-and-theme
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              # Download SPI
              wget -O /providers/custom-spi.jar "{{ .Values.initContainer.spi.url }}" || echo "Failed to download SPI"
              # Download and extract theme
              wget -O /tmp/theme.zip "{{ .Values.initContainer.theme.url }}" || echo "Failed to download theme"
              unzip /tmp/theme.zip -d /themes/ || echo "Failed to unzip theme"
              mv /themes/{{ .Values.initContainer.theme.name }} /themes/{{ .Values.initContainer.theme.name }} || echo "Failed to move theme"
              rm /tmp/theme.zip
          volumeMounts:
            - name: providers
              mountPath: /providers
            - name: themes
              mountPath: /themes
        {{- end }}    
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/opt/keycloak/bin/kc.sh"
          args:
            - {{ .Values.start.mode }}
            {{- range .Values.start.options }}
            - {{ . | quote }}
            {{- end }}
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.env.KEYCLOAK_ADMIN | quote }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.env.KEYCLOAK_ADMIN_PASSWORD | quote }}
            - name: PROXY_ADDRESS_FORWARDING
              value: {{ .Values.env.PROXY_ADDRESS_FORWARDING | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /opt/keycloak/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "keycloak.fullname" . }}-pvc
        - name: providers
          emptyDir: {}
        - name: themes
          emptyDir: {}