# keycloak/values.yaml
replicaCount: 1

image:
  repository: quay.io/keycloak/keycloak
  tag: "26.1.0"  # Use a specific version
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
  hostname: keycloak.local
  tls: false

env:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: "admin"  # Change this
  PROXY_ADDRESS_FORWARDING: "true"

serviceAccount:
  create: false

persistence:
  enabled: true
  storageClass: "standard"
  size: 8Gi

# values.yaml (add this)
start:
  mode: "start-dev"  # Options: "start" (production), "start-dev" (development)

# values.yaml
initContainer:
  enabled: true
  s3:
    bucket: "kcext"  # Replace with your bucket name
    region: "us-west-2"  # Replace with your bucket region
    spiKeys:  # List of SPI S3 object keys
      - "path/to/custom-spi-1.jar"
      - "path/to/custom-spi-2.jar"
    themeKeys:  # List of theme S3 object keys (ZIP files)
      - "path/to/custom-theme-1.zip"
      - "path/to/custom-theme-2.zip"