# keycloak/values.yaml
replicaCount: 1

image:
  repository: quay.io/keycloak/keycloak
  tag: "26.1.0"  # Use a specific version
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
  hostname: keycloak.local
  tls: false

env:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: "admin"  # Change this
  PROXY_ADDRESS_FORWARDING: "true"

serviceAccount:
  create: false

persistence:
  enabled: true
  storageClass: "standard"
  size: 8Gi

# values.yaml (add this)
start:
  mode: "start-dev"  # Options: "start" (production), "start-dev" (development)

initContainer:
  enabled: true
  spi:
    url: "https://example.com/custom-spi.jar"  # Replace with your SPI URL
  theme:
    url: "https://example.com/custom-theme.zip"  # Replace with your theme URL (zip file assumed)
    name: "custom-theme"  # Name of the theme directory after extraction