apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "keycloak.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["start", "--optimized"]
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.configuration.adminUser }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.configuration.existingSecret | default (include "keycloak.fullname" .) }}
                  key: {{ .Values.keycloak.configuration.existingSecretKey | default "admin-password" }}
            - name: KC_PROXY
              value: {{ .Values.keycloak.configuration.proxy }}
            - name: KC_HOSTNAME
              value: {{ .Values.keycloak.configuration.hostname }}
            {{- if .Values.keycloak.configuration.production }}
            - name: KC_PRODUCTION
              value: "true"
            {{- end }}
            {{- if .Values.keycloak.database.type }}
            - name: KC_DB
              value: {{ .Values.keycloak.database.type }}
            - name: KC_DB_URL
              value: jdbc:postgresql://{{ .Values.keycloak.database.host }}:{{ .Values.keycloak.database.port }}/{{ .Values.keycloak.database.database }}
            - name: KC_DB_USERNAME
              value: {{ .Values.keycloak.database.username }}
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.database.existingSecret | default (include "keycloak.fullname" .) }}
                  key: {{ .Values.keycloak.database.existingSecretKey | default "database-password" }}
            {{- end }}
            {{- if .Values.keycloak.configuration.features }}
            - name: KC_FEATURES
              value: {{ .Values.keycloak.configuration.features }}
            {{- end }}
            {{- with .Values.keycloak.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if .Values.keycloak.configuration.health.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.keycloak.configuration.health.path }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: {{ .Values.keycloak.configuration.health.path }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- with .Values.keycloak.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- with .Values.keycloak.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
