{{- if not .Values.keycloak.configuration.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.keycloak.configuration.adminPassword | b64enc | quote }}
  {{- if and .Values.keycloak.database.type (not .Values.keycloak.database.existingSecret) }}
  database-password: {{ .Values.keycloak.database.password | b64enc | quote }}
  {{- end }}
{{- end }} 