apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  containers:
    - name: keycloak
      image: quay.io/keycloak/keycloak:latest
      command: ["/opt/keycloak/bin/kc.sh"]
      args: ["start-dev"]  # Let it run normally first
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
